### ISSUE TITLE
[ERR_FR_MAX_BODY_LENGTH_EXCEEDED

### ISSUE THREAD

**Issue by sudeepcv** [rnkdsh/action-upload-diawi#11]
Run rnkdsh/action-upload-diawi@v1.1.1
Failed:  Error: Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit
    at Diawi.execute (/home/runner/work/_actions/rnkdsh/action-upload-diawi/v1.1.1/diawi.js:64:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit

**Comment by ignasi** [comment]
I guess it was fixed in #10 PR.
Could someone push a new release with the fix, please? @rnkdsh @aHejazi 
Thanks!

**Comment by rnkdsh** [comment]
> I guess it was fixed in #10 PR.
> Could someone push a new release with the fix, please? @rnkdsh @aHejazi
> Thanks!

already pushed the new version

**Comment by rnkdsh** [comment]
> Run rnkdsh/action-upload-diawi@v1.1.1
> Failed: Error: Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit
> at Diawi.execute (/home/runner/work/_actions/rnkdsh/action-upload-diawi/v1.1.1/diawi.js:64:24)
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> Error: Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit

What is the size of the APK you are trying to upload?

**Comment by ignasi** [comment]
> > I guess it was fixed in #10 PR.
> > Could someone push a new release with the fix, please? @rnkdsh @aHejazi
> > Thanks!
> 
> already pushed the new version

Are you sure? Fix is from Nov 17 and 1.1.1 is from Oct 14.

**Comment by rnkdsh** [comment]
> > > I guess it was fixed in #10 PR.
> > > Could someone push a new release with the fix, please? @rnkdsh @aHejazi
> > > Thanks!
> > 
> > 
> > already pushed the new version
> 
> Are you sure? Fix is from Nov 17 and 1.1.1 is from Oct 14.

Pushed new version. Thanks for reporting.
