### ISSUE TITLE
Not able to send custom email message

### ISSUE THREAD

**Issue by harishgupta01** [rnkdsh/action-upload-diawi#21]
Hi,

I want to include the message like if its DEV/STAGE/PROD build in the email itself. I did add this as part of comment but it appears only when you open the Diawi URL. Is there a way to add the custom message in the email itself which gets delived to all the recipient mentioned in callback_emails ?

**Comment by rnkdsh** [comment]
This feature is not supported by Diawi. We cannot change the email content. Closing the issue.
